CREATE OR REPLACE VIEW V_SALESFORECAST_PER_PRODUCT_Q_ALL_STD AS
WITH SALES_PRODUCT AS
(SELECT 
    Business_Line ,
	PRODUCT ,
	YEAR ,
    DENSE_RANK() OVER(PARTITION BY Business_Line,PRODUCT ORDER BY YEAR) DS_YEAR,
	SEASON ,
	QUANTITY ,
    LAG(QUANTITY) OVER (PARTITION BY Business_Line,PRODUCT ORDER BY YEAR,SEASON) PREV_QUANTITY,
	PRICE ,
    LAG(PRICE) OVER (PARTITION BY Business_Line,PRODUCT ORDER BY YEAR,SEASON) PREV_PRICE,
	COST ,
    LAG(COST) OVER (PARTITION BY Business_Line,PRODUCT ORDER BY YEAR,SEASON) PREV_COST,
    REVENUE,
    COGS,
    GROSS_PROFIT
FROM V_SALES_PRODUCT_DATASET_STD)

,GROWTH_SALES_PRODUCT AS
(SELECT 
    Business_Line ,
	PRODUCT ,
    DS_YEAR ,
    MAX(DS_YEAR) OVER (PARTITION BY Business_Line,PRODUCT) AS MAX_DS_YEAR,
	YEAR ,
	SEASON ,
    QUANTITY , PREV_QUANTITY,
	ROUND(((QUANTITY / NULLIF(PREV_QUANTITY,0))-1)*100,2) AS G_QUANTITY,
    PRICE , PREV_PRICE,
	ROUND(((PRICE / NULLIF(PREV_PRICE,0))-1)*100,2) AS G_PRICE,
    COST , PREV_COST,
	ROUND(((COST / NULLIF(PREV_COST,0))-1)*100,2) AS G_COST,
    REVENUE,
    COGS,
    GROSS_PROFIT
FROM SALES_PRODUCT)
, FORECAST_NEXT_YEAR AS
(SELECT 
Business_Line,
PRODUCT,
MAX(YEAR) + 1 AS FORECAST_YEAR, MAX(MAX_DS_YEAR) MAX_DS_YEAR,
AVG(G_QUANTITY) AS AVG_G_QUANTITY,
AVG(G_PRICE) AS AVG_G_PRICE,
AVG(G_COST)AS AVG_G_COST

FROM GROWTH_SALES_PRODUCT
GROUP BY Business_Line,PRODUCT)

SELECT 
    SALES_PRODUCT.Business_Line as "Business Line",
    SALES_PRODUCT.PRODUCT
	,SEASON as "Quarter"
    ,ROUND(QUANTITY,2)   AS CY_QUANTITY
    ,ROUND(QUANTITY * (1+(AVG_G_QUANTITY)/100),2) AS FC_QUANTITY
    ,ROUND(PRICE,2) AS CY_PRICE
    ,ROUND(PRICE * (1+(AVG_G_PRICE)/100),2)   AS FC_PRICE
    ,ROUND(COST,2) AS CY_COST
    ,ROUND(COST * (1+(AVG_G_COST)/100),2)  AS FC_COST
    ,ROUND(REVENUE,2) AS CY_REVENUE
    ,ROUND((QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (PRICE * (1+(AVG_G_PRICE)/100)),2) AS FC_REVENUE
    ,ROUND(COGS,2) AS CY_COGS
    ,ROUND((QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (COST * (1+(AVG_G_COST)/100)),2) AS FC_COGS
    ,ROUND(GROSS_PROFIT,2)  AS CY_GP
    ,ROUND((QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (PRICE * (1+(AVG_G_PRICE)/100)) - (QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (COST * (1+(AVG_G_COST)/100)),2) AS FC_GP
    ,ROUND((GROSS_PROFIT / REVENUE) ,2) AS CY_GM
    ,ROUND((((QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (PRICE * (1+(AVG_G_PRICE)/100)) - (QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (COST * (1+(AVG_G_COST)/100))) / 
    ((QUANTITY * (1+(AVG_G_QUANTITY)/100)) * (PRICE * (1+(AVG_G_PRICE)/100)) )),2) AS FC_GM
FROM SALES_PRODUCT 
JOIN FORECAST_NEXT_YEAR
  ON SALES_PRODUCT.PRODUCT = FORECAST_NEXT_YEAR.PRODUCT 
  WHERE YEAR = YEAR(CURRENT_DATE) - 1;